---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    -
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
    tier: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        track: stable
    spec:
      containers:
        -
          image: "registry.ng.bluemix.net/jjdojo/nginx:latest"
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/sbin/nginx
                  - "-s"
                  - quit
          name: nginx
          ports:
            -
              containerPort: 80
              name: http
          volumeMounts:
            -
              mountPath: /var/www/html/sites
              name: sites-local-storage
            -
              mountPath: /var/www/html/themes
              name: themes-local-storage
            -
              mountPath: /var/www/html/modules
              name: modules-local-storage
      imagePullSecrets:
        -
          name: image-pull
      volumes:
        -
          name: sites-local-storage
          persistentVolumeClaim:
            claimName: sites-lv-claim
        -
          name: themes-local-storage
          persistentVolumeClaim:
            claimName: themes-lv-claim
        -
          name: modules-local-storage
          persistentVolumeClaim:
            claimName: modules-lv-claim
