---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        track: stable
    spec:
      containers:
        -
          image: "registry.ng.bluemix.net/krook/nginx:latest"
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/sbin/nginx
                  - "-s"
                  - quit
          name: nginx
          ports:
            -
              containerPort: 80
              name: http
          volumeMounts:
            -
              mountPath: /content/uploads
              name: user-files-local-storage
      imagePullSecrets:
        -
          name: image-pull
      volumes:
        -
          name: user-files-local-storage
          persistentVolumeClaim:
            claimName: user-files-lv-claim
