apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: <domain> #find by running bx cs cluster-get <cluster name>
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
